# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6976572246b5d35116a7860fbd2d6485f7eaae160b5d5412763a90a6d93a4b8b8fc2c939ae761066f95b4775563338b7c50e5443eae7671137c98cc25acf2149

test:
  secret_key_base: 1fa1a38be6790b45a535e2d5f54ba2e9f476dd73c6d442e16346d07b935e48dc9afefd841828d287ee3c3016d5a294995765cd396ac01f1c206b155993ed85ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
